# This contains params to be used by the stages to train or predict

# get_ingest:
#   table_column_1: "products"
#   table_column_2: "complaints"

featurize:
  max_features: 2000
  ngrams: 3
  split: 0.2
  seed: 42


