# It contains all the configs required in the project
artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DIR: prepared
  PREPARED_DATA: prepared.pkl
  FEATURIZED_DIR: featurized
  TRAIN_DIR: train
  X_TRAIN_DATA: X_train.npy
  Y_TRAIN_DATA: y_train.npy
  TEST_DIR: test
  X_TEST_DATA: X_test.npy
  Y_TEST_DATA: y_test.npy
  MODEL_DIR: model
  MODEL_NAME: model.pkl

source_data_url:
  CF_URL: "https://files.consumerfinance.gov/ccdb/"
  ZIP_EXTENSION: "complaints.csv.zip"
  CSV_IN_ZIP: "complaints.csv"

source_download_dir:
  data_dir: data
  data_db: complaints.db
  data_table: census_complaints

metrics:
  SCORES: scores.json
